config/routes.rb
  Rails.application.routes.draw do
  resources :genres
    get '/', to: "readers#welcome" 

    get '/signup', to: "readers#new", as: "signup" 
    post '/signup', to: "readers#create"

    get '/login', to: "sessions#new", as: "login" 
    post '/login', to: "sessions#create"
    post '/logout', to: "sessions#destroy" 

    get "/auth/facebook/callback", to: "sessions#create_with_fb" 

    get '/home', to: "readers#home" 

    resources :readers, except: [:show, :index, :new, :create, :destroy, :patch, :put, :edit]  do 
      resources :books, only: [:index] 
      resources :reviews, only: [:index, :new, :create, :patch, :put, :edit] 
    end
    patch  "/reviews/:id", to: "reviews#update"

    resources :books, only: [:index, :show] do 
      resources :reviews, only: [:index] 
    end

    resources :reviews, only: [:show, :patch] 
  
    resources :genres, only: [:index] do
      resources :books, only: [:index]
    end

  #fix scope to only show items that the current_user owns
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/reader.rb
class Reader < ApplicationRecord
    has_many :reviews
    has_many :books, through: :reviews

    has_secure_password

    validates_uniqueness_of :username
    validates_presence_of :username
    
    
    validates_uniqueness_of :email
    validates_presence_of :email
end

app/controllers/readers_controller.rb
class ReadersController < ApplicationController
    before_action(:require_login, except: [:new, :create, :welcome])

    def welcome
       
    end
    
    def home
      
    end

    def index
        @readers = Reader.all
    end

    def new
        @reader = Reader.new
    end

    def show
        @reader = Reader.find_by(id: params[:id])
    end
    
    def create
        @reader = Reader.new(reader_params)
        if @reader.save
            session[:reader_id] = @reader.id
            flash[:message] = "Successfully created account!"
            redirect_to "/home"
        else
            @errors = @reader.errors.full_messages
            render :new
        end
    end

    private

    def reader_params
      params.require(:reader).permit(:username, :email, :password, :password_confirmation)
    end
  
end

app/helpers/readers_helper.rb
module ReadersHelper

    
end

app/views/readers/home.html.erb
<br>
<span class ="username"><%= current_user.username %> </span>
<h3 ><b><u>Home</u> </b>  </h3>






<% if current_user.reviews.count > 0 %>
<h3> You have written <%= current_user.reviews.count%> <%=link_to "Review(s)!", reader_reviews_path(current_user) %> </h3>
<h3> Click on your <%=link_to "Bookshelf", reader_books_path(current_user) %> to see all of your books.</h3>
<%else%>
<h4>You have not written any reviews!</h4>
<%end%>
  





<%=link_to "Write a New Review!", new_reader_review_path(current_user) %>

app/views/readers/index.html.erb
<h2> Check out the Nest Community!</h2>
<% @readers.each do |r| %>
    <li><%= link_to "#{r.username}", reader_books_path(r)%></li>
    <%end%>

app/views/readers/new.html.erb
<h1>Sign Up</h1>

<%=render(partial: "application/errors", locals: {errors: @reader.errors.full_messages})%>

<%= form_for @reader, url: signup_path do |f| %>
<%=f.label "Username"%>
<%=f.text_field :username%>
<%=f.label "Email"%>
<%=f.email_field :email%>
<%=f.label "Password"%>
<%=f.password_field :password %>
<%=f.label "Password Confirmation"%>
<%=f.password_field :password_confirmation %>
<%=f.submit "Sign Up"%>

<%end%>

<%=button_to "Sign Up With Facebook", '/auth/facebook'%>

app/views/readers/show.html.erb
<% @reader.reviews.each do |r| %>
    <li><%=link_to(r.title, review_path(r))%></li>
    <%end%>
    

app/views/readers/welcome.html.erb
<h1> Nest.</h1>

<h2>Document your experiences through your reading journey.</h2>


<% if !logged_in?%>
    <%= link_to "Log In", login_path %><br><br>
    <%= link_to "Sign Up", signup_path %>
    <% else%>
    <%= link_to "Home", home_path %>
<%end%>