config/routes.rb
  Rails.application.routes.draw do
  resources :genres
    get '/', to: "readers#welcome" 

    get '/signup', to: "readers#new", as: "signup" 
    post '/signup', to: "readers#create"

    get '/login', to: "sessions#new", as: "login" 
    post '/login', to: "sessions#create"
    post '/logout', to: "sessions#destroy" 

    get "/auth/facebook/callback", to: "sessions#create_with_fb" 

    get '/home', to: "readers#home" 

    resources :readers, except: [:show, :index, :new, :create, :destroy, :patch, :put, :edit]  do 
      resources :books, only: [:index] 
      resources :reviews, only: [:index, :new, :create, :patch, :put, :edit] 
    end
    patch  "/reviews/:id", to: "reviews#update"

    resources :books, only: [:index, :show] do 
      resources :reviews, only: [:index] 
    end

    resources :reviews, only: [:show, :patch] 
  
    resources :genres, only: [:index] do
      resources :books, only: [:index]
    end

  #fix scope to only show items that the current_user owns
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/models/book.rb
class Book < ApplicationRecord

    belongs_to :genre
    
    has_many :reviews
    has_many :readers, through: :reviews
    
    scope(:title_search, ->(title) { self.where("title like ?", "%#{title}%") })
end

app/controllers/books_controller.rb
class BooksController < ApplicationController


    def index
      
        if params[:title]  #if we search by title
          @books = Book.title_search(params[:title])
        elsif params[:reader_id] #if we are nested reader/:id/books
          @reader = Reader.find_by(id: params[:reader_id])
          
            redirect_if_not_reader(@reader)
          @books = @reader.books
        #   @books.each do |b|
        #     @review = Review.find_by(id: book.id).text 
        #   end
        # elsif params[:author_id] #if we are nested review/id/books
        #   author = Author.find_by(id: params[:author_id])
        #   @books = author.books
        else 
          @books = Book.all
        end
      
    end

    def show
        @book = Book.find_by(id: params[:id])
        
        # binding.pry
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<h3><u>Search Books By Title</u></h3>
<%= form_with url: books_path, method: :get do |f| %>
  <%=f.text_field :title %>
  <%=f. submit"Search"%>
<%end%><br>

<%if @reader%>
<h1 class = "username"><%=@reader.username %>'s Bookshelf</h1>
<%end%>

<h1>Books!</h1>

<%@books.uniq.each do |book|%>
    <li><%=link_to(book.title, book_path(book))%> - <%=link_to "Review(s)", book_reviews_path(book.id)%> : "<%= book.reviews.first.text.truncate_words(4)%>"</li><br>
  <%end%>

app/views/books/show.html.erb
<h1>Title: <%=@book.title%></h1>
<h1>Author: <%=@book.author%></h1>



<h2>Reviews:</h2>
<% @book.reviews.each do |r| %>
    <li> <span class = "username"><%= r.reader.username %></span> says: "<i><%=r.text.truncate_words(6)%>"</i> <%= link_to "more...", review_path(r.id) %><br><br></li>
    <%end%>
    