config/routes.rb
  Rails.application.routes.draw do
  resources :genres
    get '/', to: "readers#welcome" 

    get '/signup', to: "readers#new", as: "signup" 
    post '/signup', to: "readers#create"

    get '/login', to: "sessions#new", as: "login" 
    post '/login', to: "sessions#create"
    post '/logout', to: "sessions#destroy" 

    get "/auth/facebook/callback", to: "sessions#create_with_fb" 

    get '/home', to: "readers#home" 

    resources :readers, except: [:show, :index, :new, :create, :destroy, :patch, :put, :edit]  do 
      resources :books, only: [:index] 
      resources :reviews, only: [:index, :new, :create, :patch, :put, :edit] 
    end
    patch  "/reviews/:id", to: "reviews#update"

    resources :books, only: [:index, :show] do 
      resources :reviews, only: [:index] 
    end

    resources :reviews, only: [:show, :patch] 
  
    resources :genres, only: [:index] do
      resources :books, only: [:index]
    end

  #fix scope to only show items that the current_user owns
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def index
      
        if params[:reader_id]
            
            reader = Reader.find_by(id: params[:reader_id])
            redirect_if_not_reader(reader)
            @reviews = reader.reviews
        elsif params[:book_id]
                @book = Book.find_by(id: params[:book_id])
                @reviews = @book.reviews
        # else
        #     @reviews = Review.all
        end
    end

    def show
        @review = Review.find_by(id: params[:id])
      
    end

    def new
        reader = Reader.find_by(id: params[:reader_id])
        redirect_if_not_reader(reader)
        @review = Review.new
        @books = Book.all
    end

    def create
        @review = Review.create(review_params)
        @review.reader = current_user

        if params[:book_id]
            @review.book_id = params[:book_id]
        end

        if @review.save
            flash[:message] = "Successfully created!"
            redirect_to books_path
        else
              @books = Book.all
             render :new
        end
     
    end

    def edit
        reader = Reader.find_by(id: params[:reader_id])
        redirect_if_not_reader(reader)
        
        @review = Review.find_by(id: params[:id])
        # binding.pry
        if @review.reader != current_user
            flash[:message] = "That is not your review!"
            redirect_to '/reviews'
        end
    end

    def update
        
        @review = Review.find_by(id: params[:id])
        if @review.update(review_params)
            redirect_to review_path(@review.id)
        else
            render :edit
        end
    end

    def destroy

    end

    def review_params
        params.require(:review).permit(:text, :book_id, :reader_id, :id)
      end

    def set_review
    @review = Review.find_by(id: params[:id])
    end
end

app/helpers/reviews_helper.rb
module ReviewsHelper

    
end

app/views/reviews/edit.html.erb
<%=render(partial: "application/errors", locals: {errors: @review.errors.full_messages})%>

<h3>Editing review for <%=@review.book.title%></h3>

<%= form_for(@review) do |f|%>
  <%=f.label "Edit your Review here!"%>
  <%=f.text_area :text%>
  
  <%=f.submit("Save")%>
<%end%>

app/views/reviews/index.html.erb
<br><br>
<% if params[:reader_id] %>
<h2><u>Here are the reviews that you have written:</u> </h2><br/>
<% else%>
<h2> Here are the reviews for <%= @book.title %>:</h2>
<%end%>

<% @reviews.each do |r| %>
    <li><strong>"<%= r.text%>"</strong>   <% if params[:reader_id]%> <%=link_to "- #{r.book.title}", book_path(r.book.id) %> <%= link_to "Edit this Review", edit_reader_review_path(current_user, r.id)%> <% else%> <span class ="username"> <%=r.reader.username%></span> <%end%>   </li> <br>
    
    <%end%>

    <br><br>
    <% if params[:reader_id]%> <%=link_to "Write a New Review", new_reader_review_path(current_user) %> <%end%>

app/views/reviews/new.html.erb
<h1><u>Write a Review!</u></h1>

<%=render(partial: "application/errors", locals: {errors: @review.errors.full_messages})%>

<%= form_for(@review, url: reader_reviews_path(current_user) )  do |f| %>
<%=f.label "What do you think?"%> <br>
<%=f.text_area :text %> <br> <br>

<%=f.label "For which book?"%>
<%=f.collection_select(:book_id, @books, :id, :title) %>


<%=f.submit "Write a Review!"%>

<%end%>

app/views/reviews/show.html.erb
<h1><%=@review.book.title%></h1>
<h1 class ="username"><%=@review.reader.username%></h1>



<h2>Review:</h2>
<%=@review.text %>
    
    