config/routes.rb
  Rails.application.routes.draw do
  resources :genres
    get '/', to: "readers#welcome" 

    get '/signup', to: "readers#new", as: "signup" 
    post '/signup', to: "readers#create"

    get '/login', to: "sessions#new", as: "login" 
    post '/login', to: "sessions#create"
    post '/logout', to: "sessions#destroy" 

    get "/auth/facebook/callback", to: "sessions#create_with_fb" 

    get '/home', to: "readers#home" 

    resources :readers, except: [:show, :index, :new, :create, :destroy, :patch, :put, :edit]  do 
      resources :books, only: [:index] 
      resources :reviews, only: [:index, :new, :create, :patch, :put, :edit] 
    end
    patch  "/reviews/:id", to: "reviews#update"

    resources :books, only: [:index, :show] do 
      resources :reviews, only: [:index] 
    end

    resources :reviews, only: [:show, :patch] 
  
    resources :genres, only: [:index] do
      resources :books, only: [:index]
    end

  #fix scope to only show items that the current_user owns
    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project3Nest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <style>
    @import url('https://fonts.googleapis.com/css2?family=Handlee&display=swap');
    </style>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%if current_user %>
  
  <%= link_to "Home", home_path %> &nbsp
  <%=link_to "All Books", books_path %> &nbsp
  <%=link_to "My Reviews", reader_reviews_path(current_user) %> &nbsp
  <%=link_to "My Books", reader_books_path(current_user) %> &nbsp
  <%=link_to "Write a New Review", new_reader_review_path(current_user) %>
  <%= button_to "Log Out", logout_path, method: :post %>
<%else%>
    <%= link_to "Log In", login_path %> &nbsp
    <%= link_to "Sign Up", signup_path %>
<%end%>
  <%=flash[:message]%>
    <%= yield %>
  </body>
</html>